### ISSUE TITLE
MOTDs and server lists get crammed into one line after save

### ISSUE THREAD

**Issue by Cydrobolt** [ProjectFirrre/zncstrap#10]

**Comment by rika314** [comment]
I had same problem, solved it by:
```sed 's/?><? ENDLOOP ?>/?>\n<? ENDLOOP ?>/g;' /usr/local/share/znc/modules/webadmin/tmpl/*.tmpl```

**Comment by sprybear** [comment]
This should be resolved on the 'dev' branch for ZNC version 1.5 or later. Solved using the 'white-space' CSS property.
