### ISSUE TITLE
Error: Network name is a required argument

### ISSUE THREAD

**Issue by frdmn** [ProjectFirrre/zncstrap#11]
Whenever I try to change anything in the network via web admin, I get the following message:

![bildschirmfoto 2014-12-16 um 14 21 41](https://cloud.githubusercontent.com/assets/944459/5454532/22887c30-8533-11e4-8f3d-947d87e329e9.png)

Is this related to the theme? Because if I remove the symlinks and revert to the original modules/ and webskins/ folders, it works like a charm.

**Comment by sprybear** [comment]
Not quite sure myself. I updated the 'dev' branch (I'm assuming your on v1.5-git) to support the new toys. Install the latest ZNC git version and give it a try - *fingers-crossed*.

If the issue still persist, do tell. Meanwhile, will try to replicate it on my end.

**Comment by frdmn** [comment]
@sprybear awesome! I didn't even notice that branch. Works like a charm now. 

Also, the new UI changes are superb, love it!

**Comment by clovisd** [comment]
I'm having the same problem. Running VNC 1.6.2 and the latest Dev build.

![](http://i.imgur.com/Ovo003h.png)

**Comment by sprybear** [comment]
Sorry for the late one. Issue fixed #24

**Comment by clovisd** [comment]
So. While create a network works now, editing it afterwards will always result in:
![image](https://cloud.githubusercontent.com/assets/1336589/13000999/834f10a0-d11e-11e5-9d51-ba36e6265a71.png)

**Comment by sprybear** [comment]
@clovisd Yikes! Left out something there on #24 — give it a go.

**Comment by clovisd** [comment]
Fixed. Thanks! :)

**Comment by duramato** [comment]
I'm also having this issue with the latest develop version:

![img](https://pls.gtfo.accountant/upload/440eb3d0183f7f6d1e6aaa23354a9383bd34fc62.png
)
