### ISSUE TITLE
Settings pages are broken

### ISSUE THREAD

**Issue by wolfy1339** [ProjectFirrre/zncstrap#12]
A lot of the settings pages are broken, and don't display properly.
I am using znc/znc@ce1543c5ed3bfe2fa05ced840117377c8cd663d1
Also, please upgrade bootstrap.

**Comment by levifig** [comment]
Seeing issues here too: 
![screen shot 2015-01-09 at 7 11 46 pm](https://cloud.githubusercontent.com/assets/1605/5689486/c6f8ec6a-9833-11e4-8a99-9d2681cbeb76.png)

**Comment by Moter8** [comment]
Did you guys follow

```
**Q: I installed zncstrap, but it is off-margin and un-styled!**

A: You should overwrite everything from '~/zncstrap/modules' to "~/znc/share/znc/modules" on your machine.
```
from the README.md?

**Comment by wolfy1339** [comment]
First off, that folder doesn't exist, second your readme is out of date!

Everything gets installed in /usr/local/share/znc unless they install it in their home directory.

And, Yes, I followed the README.md, that's the first thing I did before touching anything.



From: Carsten H
Sent: ‎Saturday‎, ‎January‎ ‎10‎, ‎2015 ‎7‎:‎11‎ ‎AM
To: ProjectFirrre/zncstrap
Cc: Thomas Scott





Did you guys follow
**Q: I installed zncstrap, but it is off-margin and un-styled!**

A: You should overwrite everything from '~/zncstrap/modules' to "~/znc/share/znc/modules" on your machine.


from the README.md?

**Comment by Moter8** [comment]
Well this is not my project, just wanted to help.

2015-01-10 22:30 GMT+01:00 wolfy1339 <notifications@github.com>:

**Comment by frdmn** [comment]
@wolfy1339 you can update the readme and send an PR! Perhaps the repo maintainer didn't noticed this yet. 

Which version of ZNC do you use?

**Comment by wolfy1339** [comment]
i use the latest git

**Comment by frdmn** [comment]
@wolfy1339 check your developer console in your browser for any errors.

**Comment by levifig** [comment]
I never saw any error (I checked at the time) but I'll check again as well.

**Comment by sprybear** [comment]
Apologize for the late one. Very odd, I didn't receive notification from GitHub. Will check and resolve that in a bit. Excuses aside.

@wolfy1339 After installing a fresh version of ZNC (the Git version), kindly remove both 'modules' and 'webskins' folders in "/usr/local/share/znc" which belong to the default ZNC theme and replace it with zncstrap's 'modules' and 'webskins' folders instead. Do not overwrite. If you're using the latest ZNC git version 1.5 kindly switch to the 'dev' branch. 

@levifig Ahh, okay. Glad your issue has been resolved. 

@Moter8 & @frdmn Thank you for helping out. Appreciated =)

**Comment by wolfy1339** [comment]
I don't know... it still isn't working

**Comment by wolfy1339** [comment]
Now it works!

**Comment by wolfy1339** [comment]
Issue is reoccuring

**Comment by frdmn** [comment]
@wolfy1339 Um... reoccuring just like that? 

You fixed the issue the last time but didn't tell us how. Try that again then.

**Comment by wolfy1339** [comment]
I fixed part of it by just deleting znc's webskins folder and put zncstrap folder instead.
But, they are still broken, the settings page content isn't wrapped in a .container like it should be

**Comment by frdmn** [comment]
Can you give me the output of the following command please:

    ls -la /usr/local/share/znc/modules /usr/local/share/znc/webskins

**Comment by wolfy1339** [comment]
<pre>/usr/local/share/znc/modules/:
total 52
drwxr-xr-x 13 root root 4096 Jan 31 16:54 .
drwxr-xr-x  4 root root 4096 Jan 31 16:54 ..
drwxr-xr-x  3 root root 4096 Jan 31 16:54 blockuser
drwxr-xr-x  3 root root 4096 Jan 31 16:54 cert
drwxr-xr-x  3 root root 4096 Jan 31 16:54 certauth
drwxr-xr-x  3 root root 4096 Jan 31 16:54 lastseen
drwxr-xr-x  3 root root 4096 Jan 31 16:54 listsockets
drwxr-xr-x  4 root root 4096 Jan 31 16:54 notes
drwxr-xr-x  3 root root 4096 Jan 31 16:54 perform
drwxr-xr-x  3 root root 4096 Jan 31 16:54 q
drwxr-xr-x  4 root root 4096 Jan 31 16:54 send_raw
drwxr-xr-x  3 root root 4096 Jan 31 16:54 stickychan
drwxr-xr-x  4 root root 4096 Jan 31 16:54 webadmin

/usr/local/share/znc/webskins/:
total 104
drwxr-xr-x 26 root root 4096 Jan 31 16:54 .
drwxr-xr-x  4 root root 4096 Jan 31 16:54 ..
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Amelia
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Bluerex
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Cerulean
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Cirrus
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Cosmo
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Cupid
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Cyborg
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Darkly
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Flatly
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Journal
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Lumen
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Paper
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Readable
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Sandstone
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Shamrock
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Simplex
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Slate
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Spacelab
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Superhero
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Supervillain
drwxr-xr-x  4 root root 4096 Jan 31 16:54 United
drwxr-xr-x  4 root root 4096 Jan 31 16:54 WhitePlum
drwxr-xr-x  4 root root 4096 Jan 31 16:54 Yeti
drwxr-xr-x  4 root root 4096 Jan 31 16:54 _default_</pre>

**Comment by frdmn** [comment]
@wolfy1339 Strange. I would try to get rid of both folders completely, then reclone the repo and symlink them from the repo to the actual destination (`/usr/local/share/znc/{webskins,modules}`). 

Another question, do you run a caching engine like Varnish in front of your web server?
