### ISSUE TITLE
Don't specify HTTP or HTTPS in src or href

### ISSUE THREAD

**Issue by wolfy1339** [ProjectFirrre/zncstrap#15]
I've actually found a bug this time.
Don't specify http or https, you can omit those prefixes so the slashes are the first characters in the href or src. This fixes a bug about browsers complaining about using content served over HTTP on a page using HTTPS.
I saw that the bootstrap markdown JS was linked to in this html tag in the head
<code>&lt;link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown/2.1.0/js/bootstrap-markdown.js"&gt;</code> Wich should be a script tag.

**Comment by sprybear** [comment]
Spot on! Those are test script actually. Will not serve any good for the current 'dev' release.

Will remove those in a few. Thank you. (:
