### ISSUE TITLE
BindHosts textarea visual glitch

### ISSUE THREAD

**Issue by t3chguy** [ProjectFirrre/zncstrap#21]
![fireshot screen capture 035 - znc settings - znc_webdevguru_co_uk_mods_global_webadmin_settings](https://cloud.githubusercontent.com/assets/2403652/8507296/6f5d9e7a-2234-11e5-8d67-1903a7d6fe4c.png)
Pretty self explanatory

**Comment by itslukej** [comment]
Bump, this is starting to bug me now. Would be nice to see this fixed

**Comment by itslukej** [comment]
Fixed, see #29
