### ISSUE TITLE
ZNC 1.6.2 - Major Visual Glitch

### ISSUE THREAD

**Issue by itslukej** [ProjectFirrre/zncstrap#27]
Just installed ZNC and added dev zncstrap, a visual glitch is occurring

http://i.snag.gy/DixpY.jpg - Looks like this on all pages

**Comment by itslukej** [comment]
Update: Moved my ZNC to a new machine, the problem is no more.

@sprybear , Would you like me to leave this issue open in-case others are having issues with this?

**Comment by sprybear** [comment]
Glad to read that the issue has been resolved. You can go ahead and close it.

**Comment by itslukej** [comment]
😎
